#tools/llm/generate_slide_content.py
import os
import json
from openai import OpenAI
from dotenv import load_dotenv
from tools.llm.generate_sections import load_prompt

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

def generate_slide_content(lesson_objective, language_objective, lesson_content, intro_teacher, i_do_teacher, we_do_teacher):
    prompt_template = load_prompt("slide_deck")
    filled_prompt = prompt_template.format(
        lesson_objective=lesson_objective,
        language_objective=language_objective,
        lesson_content=lesson_content,
        intro_teacher=intro_teacher,
        i_do_teacher=i_do_teacher,
        we_do_teacher=we_do_teacher
    )

    print(filled_prompt)
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are an expert instructional designer returning a JSON list of slides with 'title' and 'content' keys."},
            {"role": "user", "content": filled_prompt}
        ],
        temperature=0.7
    )

    raw_output = response.choices[0].message.content.strip()
    print("🔵 Raw LLM Output:")
    print(raw_output)
    # ✅ Try parsing JSON safely
    try:
        slides = json.loads(raw_output)
    except json.JSONDecodeError:
        # Try to clean up fancy quotes
        cleaned = raw_output.replace("“", "\"").replace("”", "\"").replace("‘", "'").replace("’", "'")
        slides = json.loads(cleaned)

    # ✅ Validate structure
    valid_slides = []
    for s in slides:
        if isinstance(s, dict) and "title" in s and "content" in s:
            valid_slides.append(s)
        else:
            print("⚠️ Invalid slide entry:", s)

    if not valid_slides:
        raise ValueError("No valid slides generated by LLM")

    return valid_slides
